server:
  port: 5005

spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/dayveedo1/config-server
          default-label: main
          clone-on-start: true



